version: "3.8"

services:
  mysql:
    build:
      context: ./dataaccess  # Path to the MySQL Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kodomo
    ports:
      - "3307:3307"  # This allows local access for debugging, but not strictly necessary for the Flask app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    restart: always
    
  flask_app:
    build:
      context: .  # Path to the Flask Dockerfile
    container_name: flask_app_container
    ports:
      - "8080:8080"  # Expose Flask app on port 8080
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql  # Service name for MySQL in the Compose network
      MYSQL_PORT: 3306   # Default MySQL port
      MYSQL_DATABASE: kodomo
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
